name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v5.1.0
      with:
        build-args: "PLATFORM=storage"
        file: Dockerfile
        tags: robert-oleynik/storage-service:$(date +%s)
